/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostIdImport } from './routes/$postId'
import { Route as PreviewPostIdImport } from './routes/preview/$postId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PostIdRoute = PostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PreviewPostIdRoute = PreviewPostIdImport.update({
  id: '/preview/$postId',
  path: '/preview/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$postId': {
      id: '/$postId'
      path: '/$postId'
      fullPath: '/$postId'
      preLoaderRoute: typeof PostIdImport
      parentRoute: typeof rootRoute
    }
    '/preview/$postId': {
      id: '/preview/$postId'
      path: '/preview/$postId'
      fullPath: '/preview/$postId'
      preLoaderRoute: typeof PreviewPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$postId': typeof PostIdRoute
  '/preview/$postId': typeof PreviewPostIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$postId': typeof PostIdRoute
  '/preview/$postId': typeof PreviewPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$postId': typeof PostIdRoute
  '/preview/$postId': typeof PreviewPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$postId' | '/preview/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$postId' | '/preview/$postId'
  id: '__root__' | '/' | '/$postId' | '/preview/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PostIdRoute: typeof PostIdRoute
  PreviewPostIdRoute: typeof PreviewPostIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PostIdRoute: PostIdRoute,
  PreviewPostIdRoute: PreviewPostIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$postId",
        "/preview/$postId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$postId": {
      "filePath": "$postId.tsx"
    },
    "/preview/$postId": {
      "filePath": "preview/$postId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
